language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  licenses:
  - ".+"
before_install:
- openssl aes-256-cbc -K $encrypted_bd40e8f78fa4_key -iv $encrypted_bd40e8f78fa4_iv
  -in TravisBuild-Keystore.jks.enc -out TravisBuild-Keystore.jks -d
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
sudo: required
install: true
before_script:
- chmod +x gradlew
script:
- "./gradlew assembleRelease --stacktrace"
deploy:
  provider: releases
  api_key:
    secure: RKk+IyPvMRbC9Ki4tq/W12XkmEWCdVbRmBd7xJyaQY3IC8QSe97VrNyTkOyFsGCcvue9PJUFmhFyGbdZnAwT79qr7lGer0hWFYGn1+FIGQRNEipXpG80Dosex9mFN94FbdIGndKKQeUjwIEwa1a2xcR6V1BOtFWrefK3sXl1XNHlbmgfEOEBM8or2ZTWd991jc29Tq3YsNzh9gKjw/j7+iiHwXKF+iEchq1R6KD5pQRU31seWVp9zrStF7n7GRHvhJNdwAzUd+2I0i97wG+UcUdoWMAGKtzdXAzo75QCfxDrE3kTwgJT2jiXDTqXnmw+LbCePhluXVOC99OxJiaPqfM+jG+1/R+IKd17qJEDuf6jMPFVrDeUilbAyHr4b+sShEPoJu5Nnm1tFj/MkDjY7e/TO+Uq/yw/AxOpAh7lShz/hreCkQkvJxDVRK2NInE1Yrn5SaUX1JFH0CjgExbF8otWFaBn9+5LPSfCQhUOFMDnM0zjgY4O++JLZWDnsYUY+7JzYUarV4Kyf7AtYFZCaNL36JZvtqrNq75QimdiJ6v43rs+O4crV85HmQAp/7ies4n6PUt78ksa7nAhXpCutv9odohzMV+9y9QbPabWj/yo7zIDFHXY4WUVBp1DP2WI7DlyvRqWTt2Bf2TTR5DNcb1bDo5aMtChHnekUvBM8Is=
  file: app/build/outputs/apk/release/*.apk
  on:
    repo: bkhezry/TravisCIBuildTest
    only:
      - master
      - /v\d+\.\d+[a-z]/

